services:
  # Veritabanı servis adı görseldeki URL ile BİREBİR aynı olmalı
  mongo.db.catalog:
    image: mongo:8.0-rc
    container_name: catalog_mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "27030:27017"
    volumes:
      - mongo.db.catalog.volume:/data/db

  # UI Servisi (Görseldeki Yapı)
  catalog-db-ui:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: catalog_mongo_ui
    restart: always
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongo.db.catalog:27017/
      ME_CONFIG_BASICAUTH: false
    ports:
      - "27018:8081"
    depends_on:
      - mongo.db.catalog
  redis.db.basket:
    restart: always
    image: redis:7.0-rc
    container_name: basket_redis_db
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
     - redis.db.basket.volume:/data
  redis.db.basket.ui:
    restart: always
    image: rediscommander/redis-commander:redis-commander-210
    container_name: basket_redis_ui
    environment:
       REDIS_HOSTS: local:redis.db.basket:6379:0:${REDIS_PASSWORD}
       HTTP_USER: ${REDIS_UI_USER}
       HTTP_PASSWORD: ${REDIS_UI_PASSWORD}
    ports:
      - "27019:8081"
    depends_on:
      - redis.db.basket

volumes:
  mongo.db.catalog.volume:
  redis.db.basket.volume: