services:
  # Veritabanı servis adı görseldeki URL ile BİREBİR aynı olmalı
  mongo.db.catalog:
    image: mongo:8.0-rc
    container_name: catalog_mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "27030:27017"
    volumes:
      - mongo.db.catalog.volume:/data/db
  catalog-db-ui:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: catalog_mongo_ui
    restart: always
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongo.db.catalog:27017/
      ME_CONFIG_BASICAUTH: false
    ports:
      - "27018:8081"
    depends_on:
      - mongo.db.catalog
  redis.db.basket:
    restart: always
    image: redis:7.0-rc
    container_name: basket_redis_db
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
     - redis.db.basket.volume:/data
  redis.db.basket.ui:
    restart: always
    image: rediscommander/redis-commander:redis-commander-210
    container_name: basket_redis_ui
    environment:
       REDIS_HOSTS: local:redis.db.basket:6379:0:${REDIS_PASSWORD}
       HTTP_USER: ${REDIS_UI_USER}
       HTTP_PASSWORD: ${REDIS_UI_PASSWORD}
    ports:
      - "27019:8081"
    depends_on:
      - redis.db.basket
  mongo.db.discount:
    image: mongo:8.0-rc
    container_name: discount_mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "27034:27017"
    volumes:
      - mongo.db.discount.volume:/data/db
  discount-db-ui:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: discount_mongo_ui
    restart: always
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongo.db.discount:27017/
      ME_CONFIG_BASICAUTH: false
    ports:
      - "27020:8081"
    depends_on:
      - mongo.db.discount
  sqlserver.order.db:
     image: mcr.microsoft.com/mssql/server:2022-latest
     container_name: "sqlserver.order"
     restart: always
     environment: 
        - ACCEPT_EULA=Y 
        - SA_PASSWORD=${DB_PASSWORD} 
     ports: 
        - "1433:1433"
     volumes:
        - "sqlserver.orderdb.volume:/var/opt/mssql"
  keycloak:
    restart: always
    container_name: keycloak.container
    image: quay.io/keycloak/keycloak:25.0
    command: start
    environment:
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HOSTNAME_STRICT: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres.db.keycloak/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
        - "8080:8080"
    depends_on:
      - postgres.db.keycloak
  postgres.db.keycloak:
    restart: always
    image: postgres:16.2
    container_name: postgres.db.keycloak.container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
        - "5432:5432"
    volumes:
      - postgres.db.keycloak.volume:/var/lib/postgresql/data
  postgres.db.keycloak.ui:
    restart: always
    image: dpage/pgadmin4
    container_name: postgres.db.keycloak.container.ui
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - postgres.db.keycloak.ui.volume:/var/lib/pgadmin
volumes:
  mongo.db.catalog.volume:
  mongo.db.discount.volume:
  redis.db.basket.volume:
  sqlserver.orderdb.volume:
  postgres.db.keycloak.volume:
  postgres.db.keycloak.ui.volume:  