@BaseUrl = http://localhost:5142


POST {{BaseUrl}}/api/v1/discounts
Accept: application/json
Content-Type: application/json
{
  "userId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "code": "A1B2C3D4E5",
  "rate": 10
}
###
GET {{BaseUrl}}/api/v1/discounts/A1B2C3D4
Accept: application/json

###
