@baseUrl = http://localhost:5101
@categoryId = 08debc96-96b4-6fb6-0250-410000010000
@courseId= 08debd75-408f-01f3-0250-410000010000
GET {{baseUrl}}/api/categories
Accept: application/json
###

POST {{baseUrl}}/api/categories
Accept: application/json
Content-Type: application/json
{
  "name": "Category test"
}
###

GET {{baseUrl}}/api/categories/{{categoryId}}
Accept: application/json
###

POST {{baseUrl}}/api/courses
Accept: application/json
Content-Type:application/json
{
  "name": "course name 1",
  "description": "test",
  "price": 100,
  "imageUrl": "test image url",
  "categoryId": "{{categoryId}}"
}
###
PUT {{baseUrl}}/api/courses
Accept: application/json
Content-Type:application/json
{
  "id": "{{courseId}}",
  "name": "course name update",
  "description": "test update",
  "price": 100.99,
  "imageUrl": "test image url",
  "categoryId": "{{categoryId}}"
}
###
GET {{baseUrl}}/api/courses
Accept: application/json
###

GET {{baseUrl}}/api/courses/{{courseId}}
Accept: application/json