@baseUrl = http://localhost:5101
@categoryId = 08debf05-b8af-db9a-f875-a4e015e70000
@courseId= 08debd75-408f-01f3-0250-410000010000
@userId= 08debf05-b8eb-21db-f875-a4e015e70000
GET {{baseUrl}}/api/categories
Accept: application/json
###

POST {{baseUrl}}/api/categories
Accept: application/json
Content-Type: application/json
{
  "name": "Category test"
}
###

GET {{baseUrl}}/api/categories/{{categoryId}}
Accept: application/json
###

POST {{baseUrl}}/api/courses
Accept: application/json
Content-Type:application/json
{
  "name": "course name 1",
  "description": "test",
  "price": 100,
  "imageUrl": "test image url",
  "categoryId": "{{categoryId}}"
}
###
PUT {{baseUrl}}/api/courses
Accept: application/json
Content-Type:application/json
{
  "id": "{{courseId}}",
  "name": "course name update",
  "description": "test update",
  "price": 100.99,
  "imageUrl": "test image url",
  "categoryId": "{{categoryId}}"
}
###
DELETE {{baseUrl}}/api/courses/{{courseId}}
Accept: application/json
###
GET {{baseUrl}}/api/courses
Accept: application/json
###

GET {{baseUrl}}/api/courses/{{courseId}}
Accept: application/json

###
GET {{baseUrl}}/api/courses/user/{{userId}}
Accept: application/json