@baseUrl = http://localhost:5151
@courseId = 3fa85f64-5717-4562-b3fc-2c963f66afa6

POST {{baseUrl}}/api/v1/baskets/item
Accept: application/json
Content-Type: application/json
{
  "courseId": "{{courseId}}",
  "courseName": "test course yeni",
  "imageUrl": "test-image.png",
  "price": 100
}

###
GET {{baseUrl}}/api/v1/baskets/user
Accept: application/json

###
DELETE {{baseUrl}}/api/v1/baskets/item/{{courseId}}
Accept: application/json


