@baseUrl = http://localhost:5151
@courseId = 3fa85f64-5717-4562-b3fc-2c963f66af12

POST {{baseUrl}}/api/v1/baskets/item
Accept: application/json
Content-Type: application/json
{
  "courseId": "{{courseId}}",
  "courseName": "test course yeni3",
  "imageUrl": "test-image.png",
  "price": 50
}

###
GET {{baseUrl}}/api/v1/baskets/user
Accept: application/json

###
DELETE {{baseUrl}}/api/v1/baskets/item/{{courseId}}
Accept: application/json

###
PUT {{baseUrl}}/api/v1/baskets/apply-discount-coupon
Accept: application/json
Content-Type: application/json
{
  "discountRate": 0.25,
  "coupon": "TESTCOUPON"
}

###
DELETE {{baseUrl}}/api/v1/baskets/remove-discount-coupon
Accept: application/json

